### PR TITLE
Environment setting

### PR DESCRIPTION
**Pull request by ibonly**
Added environment variable to increase the security of the database

### CODE REVIEW

**Comment by alexschwarz89** [comment]
Hi @andela-iadeniyi , thanks for your contribution. It's a nice idea to support .ENV files! 

To ensure that the library works fine if called over CLI (there's no`$_SERVER` available) could you call `self::loadEnv();` only inside the first `if`-condition? Also the last `getenv('DATABASE_NAME');` in the else block seems like a mistake?

After that i will be happy to accept the PR. Thanks again for contributing.

**Comment by ibonly** [comment]
Ok, cool. I will update that.

**Comment by ibonly** [comment]
@alexschwarz89: Updated

**Comment by ibonly** [comment]
Hi @alexschwarz89, still waiting for your response on this `PR`

**Comment by alexschwarz89** [comment]
All merged an done, thanks again @andela-iadeniyi

**Pull request merged**
